ci:
  autoupdate_commit_msg: "chore: update pre-commit hooks"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.5.0"
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: mixed-line-ending
      - id: detect-private-key
      - id: check-ast

  - repo: https://github.com/pycqa/flake8
    rev: '4.0.1'  # Use the latest flake8 version or the one you prefer
    hooks:
      - id: flake8
        args: ['--select=F821,F822,F831,E111,E112,E113,E999,E902']

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.3.5' # current Ruff version.
    hooks:
      - id: ruff-format # run the formatter
